% Plot pop_front benchmark results with a linked-list zoom view.
clear
clc
close all;

set(groot, 'defaultAxesXColor', 'k');
set(groot, 'defaultAxesYColor', 'k');
set(groot, 'defaultTextColor', 'k');
set(groot, 'defaultAxesGridColor', [0.8 0.8 0.8]);
set(groot, 'defaultFigureColor', 'w');
set(groot, 'defaultAxesColor', 'w');

% Load the exported CSV for the pop_front operation.
path = '/Volumes/KN/Studia/Semestr4/Struktury danych/Projekt 1/Matlab/results/n=100/pop_front.csv';
data = readtable(path);

x = data.Size;
dynamicArray = data.DynamicArray;
singlyLinkedList = data.SinglyLinkedList;
doublyLinkedList = data.DoublyLinkedList;

figure('Color', 'w', 'Position', [100 100 1400 900]);

tiledlayout(2,1, ...
    'TileSpacing', 'loose', ...
    'Padding', 'loose');

% =========================
% Main plot
% =========================
nexttile;

h0 = scatter(x, dynamicArray, 35, ...
    'filled', ...
    'MarkerFaceColor', [0 0.4470 0.7410], ...
    'MarkerEdgeColor', [0 0.4470 0.7410]);
hold on;

h1 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.5 0], ...
    'MarkerEdgeColor', [1 0.5 0]);

h2 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [0.95 0.8 0.2], ...
    'MarkerEdgeColor', [0.95 0.8 0.2]);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

ylabel('Average execution time $[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

grid on;
box on;

set(gca, ...
    'FontSize', 13, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 max(dynamicArray) * 1.1]);

% Regression only for Dynamic Array
p1 = polyfit(x, dynamicArray, 1);
yfit1 = polyval(p1, x);

R1 = 1 - sum((dynamicArray - yfit1).^2) / ...
    sum((dynamicArray - mean(dynamicArray)).^2);

h3 = plot(x, yfit1, '--', ...
    'LineWidth', 1.5, ...
    'Color', [0 0.4470 0.7410]);

lgd = legend([h0 h1 h2 h3], ...
    {'Dynamic Array', ...
     'Singly Linked List', ...
     'Doubly Linked List', ...
     'DA regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd.TextColor = 'k';
lgd.Color = 'w';
lgd.EdgeColor = 'k';

text(0.22, 0.883, ...
    sprintf(['Dynamic Array regression:\n' ...
             '$y = %.6fx + %.2f$\n' ...
             '$R^2 = %.4f$'], ...
             p1(1), p1(2), R1), ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

% =========================
% Zoom plot
% =========================
nexttile;

h4 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.5 0], ...
    'MarkerEdgeColor', [1 0.5 0]);
hold on;

h5 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [0.95 0.8 0.2], ...
    'MarkerEdgeColor', [0.95 0.8 0.2]);

% Regression for Singly Linked List
p0 = polyfit(x, singlyLinkedList, 1);
yfit0 = polyval(p0, x);

h6 = plot(x, yfit0, '--', ...
    'LineWidth', 1.2, ...
    'Color', [1 0.5 0]);

% Regression for Doubly Linked List
p2 = polyfit(x, doublyLinkedList, 1);
yfit2 = polyval(p2, x);

h7 = plot(x, yfit2, '--', ...
    'LineWidth', 1.2, ...
    'Color', [0.95 0.8 0.2]);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

ylabel('$t\,[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

title('Zoom on Singly Linked List and Doubly Linked List', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

lgd1 = legend([h4 h5 h6 h7], ...
    {'Singly Linked List', ...
     'Doubly Linked List', ...
     'SLL regression', ...
     'DLL regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd1.TextColor = 'k';
lgd1.Color = 'w';
lgd1.EdgeColor = 'k';

grid on;
box on;

set(gca, ...
    'FontSize', 12, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1);

xlim([0 max(x) * 1.05]);
ylim([0 150]);

text(0.22, 0.944, ...
    sprintf(['SLL: $y = %.6fx + %.2f$\n' ...
             'DLL: $y = %.6fx + %.2f$'], ...
             p0(1), p0(2), ...
             p2(1), p2(2)), ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

set(gcf, 'Renderer', 'painters');
drawnow;

exportgraphics(gcf, 'pop_front_benchmark.png', ...
    'Resolution', 300);