% Plot push_back benchmark results for each tested structure.
clear
clc
close all;

set(groot, 'defaultAxesXColor', 'k');
set(groot, 'defaultAxesYColor', 'k');
set(groot, 'defaultTextColor', 'k');
set(groot, 'defaultAxesGridColor', [0.8 0.8 0.8]);
set(groot, 'defaultFigureColor', 'w');
set(groot, 'defaultAxesColor', 'w');

% Load the exported CSV for the push_back operation.
path = '/Volumes/KN/Studia/Semestr4/Struktury danych/Projekt 1/Matlab/results/n=100/push_back.csv';
data = readtable(path);


x = data.Size;
dynamicArray = data.DynamicArray;
singlyLinkedList = data.SinglyLinkedList;
doublyLinkedList = data.DoublyLinkedList;

figure('Color', 'w', 'Position', [100 100 1400 800]);

tiledlayout(3,1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

% =========================
% Dynamic array plot
% =========================
nexttile;

h0 = scatter(x, dynamicArray, 35, ...
    'filled', ...
    'MarkerFaceColor', [0 0.4470 0.7410], ...
    'MarkerEdgeColor', [0 0.4470 0.7410]);
hold on;

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

ylabel('$t\,[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

grid on;
box on;

set(gca, ...
    'FontSize', 12, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 60]);

% Linear regression for Dynamic Array
p0 = polyfit(x, dynamicArray, 1);
yfit0 = polyval(p0, x);

color0 = [0 0.4470 0.7410];

h1 = plot(x, yfit0, '--', ...
    'LineWidth', 1.5, ...
    'Color', color0);

lgd = legend([h0 h1], ...
    {'Dynamic Array', 'Dynamic Array regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd.TextColor = 'k';
lgd.Color = 'w';
lgd.EdgeColor = 'k';

text(0.75, 0.33, ...
    sprintf(['Dynamic Array regression:\n' ...
             '$y = %.6fx + %.2f$'], ...
             p0(1), p0(2)), ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

% =========================
% Singly linked list plot
% =========================
nexttile;

h2 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.5 0], ...
    'MarkerEdgeColor', [1 0.5 0]);
hold on;

p1 = polyfit(x, singlyLinkedList, 1);
yfit1 = polyval(p1, x);

h3 = plot(x, yfit1, '--', ...
    'LineWidth', 1.2, ...
    'Color', [1 0.5 0]);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

ylabel('$t\,[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

text(0.75, 0.3, ...
    sprintf(['SLL: y = %.6fx + %.2f'], ...
             p1(1), p1(2)), ...
    'Units', 'normalized', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

lgd1 = legend([h2 h3], ...
    {'Singly Linked List', ...
     'SLL regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd1.TextColor = 'k';
lgd1.Color = 'w';
lgd1.EdgeColor = 'k';

grid on;
box on;

set(gca, ...
    'FontSize', 12, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 60]);

% =========================
% Doubly linked list plot
% =========================
nexttile;

h4 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [0.95 0.8 0.2], ...
    'MarkerEdgeColor', [0.95 0.8 0.2]);
hold on;

p2 = polyfit(x, doublyLinkedList, 1);
yfit2 = polyval(p2, x);

h5 = plot(x, yfit2, '--', ...
    'LineWidth', 1.2, ...
    'Color', [0.95 0.8 0.2]);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

ylabel('$t\,[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

text(0.75, 0.3, ...
    sprintf(['DLL: y = %.6fx + %.2f'], ...
             p2(1), p2(2)), ...
    'Units', 'normalized', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

lgd2 = legend([h4 h5], ...
    {'Doubly Linked List', ...
     'DLL regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'southwest', ...
    'FontSize', 16);

lgd2.TextColor = 'k';
lgd2.Color = 'w';
lgd2.EdgeColor = 'k';

grid on;
box on;

set(gca, ...
    'FontSize', 12, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 60]);

exportgraphics(gcf, 'push_back_benchmark.png', ...
    'Resolution', 300);
