% Plot push_front benchmark results and fitted trend lines.
clear
clc
close all;

set(groot, 'defaultAxesXColor', 'k');
set(groot, 'defaultAxesYColor', 'k');
set(groot, 'defaultTextColor', 'k');
set(groot, 'defaultAxesGridColor', [0.8 0.8 0.8]);
set(groot, 'defaultFigureColor', 'w');
set(groot, 'defaultAxesColor', 'w');

% data = readtable('pop_back.csv');
% data = readtable('pop_front.csv');
% data = readtable('remove.csv');

% Load the exported CSV for the push_front operation.
path = '/Volumes/KN/Studia/Semestr4/Struktury danych/Projekt 1/Matlab/results/n=100/push_front.csv';
data = readtable(path);


x = data.Size;
dynamicArray = data.DynamicArray;
singlyLinkedList = data.SinglyLinkedList;
doublyLinkedList = data.DoublyLinkedList;

figure('Color', 'w', 'Position', [100 100 1400 900]);

tiledlayout(2,1, 'TileSpacing', 'compact', 'Padding', 'compact');

% =========================
% Main plot
% =========================
nexttile;

h0 = scatter(x, dynamicArray, 35, ...
    'filled', ...
    'MarkerFaceColor', [0 0.4470 0.7410], ...
    'MarkerEdgeColor', [0 0.4470 0.7410]);
hold on;

h1 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.5 0], ...
    'MarkerEdgeColor', [1 0.5 0]);

h2 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [0.95 0.8 0.2], ...
    'MarkerEdgeColor', [0.95 0.8 0.2]);

rectangle( ...
    'Position', [0 0 max(x) 220], ...
    'EdgeColor', 'k', ...
    'LineStyle', '--', ...
    'LineWidth', 1.5);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20);

ylabel('Average execution time $[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

grid on;
box on;

set(gca, ...
    'FontSize', 13, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 max(dynamicArray) * 1.1]);

% Colors
color0 = [0 0.4470 0.7410];
color1 = [1 0.5 0];
color2 = [0.95 0.8 0.2];

% Linear regression for Dynamic Array
p0 = polyfit(x, dynamicArray, 1);
yfit0 = polyval(p0, x);

R0 = 1 - sum((dynamicArray - yfit0).^2) / ...
    sum((dynamicArray - mean(dynamicArray)).^2);

h3 = plot(x, yfit0, '--', ...
    'LineWidth', 1.5, ...
    'Color', color0);

lgd = legend([h0 h1 h2 h3], ...
    {'Dynamic Array', 'Singly Linked List', ...
     'Doubly Linked List', 'Dynamic Array regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd.TextColor = 'k';
lgd.Color = 'w';
lgd.EdgeColor = 'k';

text(0.011, 0.63, ...
    sprintf(['Dynamic Array regression:\n' ...
             '$y = %.6fx + %.2f$\n' ...
             '$R^2 = %.4f$'], ...
             p0(1), p0(2), R0), ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');
% =========================
% Zoom plot
% =========================
nexttile;

h1 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.5 0], ...
    'MarkerEdgeColor', [1 0.5 0]);
hold on;

h2 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', [1 0.8 0.2], ...
    'MarkerEdgeColor', [1 0.8 0.2]);

color1 = [1 0.5 0];
color2 = [0.95 0.8 0.2];

% Linear regression for Singly Linked List
p1 = polyfit(x, singlyLinkedList, 1);
yfit1 = polyval(p1, x);

plot(x, yfit1, '--', ...
    'LineWidth', 1.2, ...
    'Color', color1);

% Linear regression for Doubly Linked List
p2 = polyfit(x, doublyLinkedList, 1);
yfit2 = polyval(p2, x);

plot(x, yfit2, '--', ...
    'LineWidth', 1.2, ...
    'Color', color2);


% Add regression equations and R^2 values
text(0.011, 0.63, ...
    sprintf(['SLL: y = %.6fx + %.2f\n' ...
             'DLL: y = %.6fx + %.2f'], ...
             p1(1), p1(2), ...
             p2(1), p2(2)), ...
    'Units', 'normalized', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');
xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

ylabel('$t\,[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 14);

title('Zoom on linked lists', ...
    'Interpreter', 'latex', ...
    'FontSize', 1);

lgd1 = legend( ...
    {'Singly Linked List', 'Doubly Linked List', ...
     'SLL regression', 'DLL regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd1.TextColor = 'k';
lgd1.Color = 'w';
lgd1.EdgeColor = 'k';

grid on;
box on;

set(gca, ...
    'FontSize', 12, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1);

xlim([0 max(x) * 1.05]);
ylim([0 100]);


exportgraphics(gcf, 'push_front_benchmark.png', 'Resolution', 300);
