% Plot remove benchmark results and compare linear trends.
clear
clc
close all;

set(groot, 'defaultAxesXColor', 'k');
set(groot, 'defaultAxesYColor', 'k');
set(groot, 'defaultTextColor', 'k');
set(groot, 'defaultAxesGridColor', [0.8 0.8 0.8]);
set(groot, 'defaultFigureColor', 'w');
set(groot, 'defaultAxesColor', 'w');

% Load the exported CSV for the remove operation.
path = '/Volumes/KN/Studia/Semestr4/Struktury danych/Projekt 1/Matlab/results/n=100/remove.csv';
data = readtable(path);

% Use only first 45 measurements to remove anomalous tail values
x = data.Size(1:50);
dynamicArray = data.DynamicArray;
singlyLinkedList = data.SinglyLinkedList;
doublyLinkedList = data.DoublyLinkedList;

figure('Color', 'w', 'Position', [100 100 1400 700]);

color0 = [0 0.4470 0.7410];
color1 = [1 0.5 0];
color2 = [0.95 0.8 0.2];

h0 = scatter(x, dynamicArray, 35, ...
    'filled', ...
    'MarkerFaceColor', color0, ...
    'MarkerEdgeColor', color0);
hold on;

h1 = scatter(x, singlyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', color1, ...
    'MarkerEdgeColor', color1);

h2 = scatter(x, doublyLinkedList, 35, ...
    'filled', ...
    'MarkerFaceColor', color2, ...
    'MarkerEdgeColor', color2);

% Dynamic Array regression
p0 = polyfit(x, dynamicArray, 1);
yfit0 = polyval(p0, x);
R0 = 1 - sum((dynamicArray - yfit0).^2) / ...
    sum((dynamicArray - mean(dynamicArray)).^2);

h3 = plot(x, yfit0, '--', ...
    'LineWidth', 1.5, ...
    'Color', color0);

% Singly Linked List regression
p1 = polyfit(x, singlyLinkedList, 1);
yfit1 = polyval(p1, x);
R1 = 1 - sum((singlyLinkedList - yfit1).^2) / ...
    sum((singlyLinkedList - mean(singlyLinkedList)).^2);

h4 = plot(x, yfit1, '--', ...
    'LineWidth', 1.5, ...
    'Color', color1);

% Doubly Linked List regression
p2 = polyfit(x, doublyLinkedList, 1);
yfit2 = polyval(p2, x);
R2 = 1 - sum((doublyLinkedList - yfit2).^2) / ...
    sum((doublyLinkedList - mean(doublyLinkedList)).^2);

h5 = plot(x, yfit2, '--', ...
    'LineWidth', 1.5, ...
    'Color', color2);

xlabel('$n$', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

ylabel('Average execution time $[ns]$', ...
    'Interpreter', 'latex', ...
    'FontSize', 16);

grid on;
box on;

set(gca, ...
    'FontSize', 13, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth', 1.2);

xlim([0 max(x) * 1.05]);
ylim([0 max([dynamicArray; singlyLinkedList; doublyLinkedList]) * 1.15]);

lgd = legend([h0 h1 h2 h3 h4 h5], ...
    {'Dynamic Array', ...
     'Singly Linked List', ...
     'Doubly Linked List', ...
     'DA regression', ...
     'SLL regression', ...
     'DLL regression'}, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'FontSize', 16);

lgd.TextColor = 'k';
lgd.Color = 'w';
lgd.EdgeColor = 'k';

text(0.02, 0.64, ...
    sprintf(['DA: $y = %.6fx + %.2f$, $R^2 = %.4f$\n' ...
             'SLL: $y = %.6fx + %.2f$, $R^2 = %.4f$\n' ...
             'DLL: $y = %.6fx + %.2f$, $R^2 = %.4f$'], ...
             p0(1), p0(2), R0, ...
             p1(1), p1(2), R1, ...
             p2(1), p2(2), R2), ...
    'Units', 'normalized', ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'VerticalAlignment', 'top', ...
    'BackgroundColor', 'white', ...
    'EdgeColor', 'black');

cd('/Volumes/KN/Studia/Semestr4/Struktury danych/Projekt 1/Matlab')

exportgraphics(gcf, 'remove_benchmark.png', ...
    'Resolution', 300);